on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python.version:
        - pypy3
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - 3.7
    steps:
    - uses: actions/checkout@v2
    - name: Use cached Python ${{ matrix.python.version }} for tests.
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python.version }}
    - name: Install dependencies
      run: pip install --upgrade pip nox
    - name: nox --session ${{ env.nox.env }}
      run: nox -e ${{ env.nox.env }}

